### ISSUE TITLE
Sponsors - Add Pivotal as a Bronze Sponsor

### ISSUE THREAD

**Issue by paulrayner** [paulrayner/exploreddd.github.com#70]
Pivotal info is on the Google Drive, in [Explore DDD/2018/Website/Sponsors/Pivotal](https://drive.google.com/open?id=1kBrmW3EeUDFy-Ng9HvC0nL0eAO7Qz85s).

Add to sponsors page. Logo should also be at bottom of pages in sponsors section...as a bronze sponsor the logo at the bottom of the page is approx 2/3 the size of the Alteryx logo was last year.

**Comment by paulrayner** [comment]
@PowrSlave - Pivotal is a bronze sponsor, so their Sponsor page heading should be "Bronze Sponsor" instead of "Platinum Sponsor". Later, when/if we add higher sponsorship levels (Platinum, Gold, Silver etc.) they'll go above the Bronze sponsors.

**Comment by PowrSlave** [comment]
Yeah I left this one half complete since I had a meeting, but I've since corrected it. It was an unusually chaotic day :/

**Comment by PowrSlave** [comment]
Ok. So I created a new css class to apply only to bronze sponsors in the footer. I imagine those will likely be listed after the larger platinum and gold sponsors so that the UI flow in the footer area is more logical. For now it's just the one sponsor, so we can check into this as other sponsors are added.

**Comment by paulrayner** [comment]
Good idea. Thanks.
